# Generated by Django 2.2.5 on 2019-09-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_create_book_and_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='page',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
